language: rust
sudo: required
dist: trusty
rust:
  - stable
  - beta
  - nightly
cache: cargo
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
matrix:
  allow_failures:
  - rust: nightly
